import fs from 'node:fs';
import { Dex } from '@pkmn/dex';
import { Generations } from '@smogon/calc';

const RULESET_PATH = 'src/data/championsRulesets.ts';
const OUTPUT_PATH = 'src/data/learnableAttackMoves.ts';

function extractStringArray(source, propertyName) {
  const match = source.match(new RegExp(`${propertyName}: \\[([\\s\\S]*?)\\]`));
  if (!match) {
    throw new Error(`Could not find ${propertyName} in ${RULESET_PATH}`);
  }

  return [...match[1].matchAll(/'([^']+)'/g)].map((item) => item[1]);
}

function uniqueSorted(values) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right, 'en'));
}

function fallbackLearnsetNames(species) {
  const names = [species.name, species.baseSpecies];
  const dexSpecies = Dex.species.get(species.name);

  names.push(dexSpecies.baseSpecies);

  if (species.name.includes('-Mega')) {
    names.push(species.name.replace(/-Mega.*$/, ''));
    names.push(species.baseSpecies?.replace(/-Mega.*$/, ''));
  }

  if (species.name.startsWith('Aegislash-')) {
    names.push('Aegislash');
  }

  return uniqueSorted(names.filter(Boolean));
}

async function learnsetMoveIdsForSpecies(species) {
  for (const name of fallbackLearnsetNames(species)) {
    const learnsetData = await Dex.learnsets.get(name);
    const moveIds = Object.keys(learnsetData.learnset ?? {});
    if (moveIds.length > 0) return moveIds;
  }

  return [];
}

const rulesetSource = fs.readFileSync(RULESET_PATH, 'utf8');
const baseSpecies = extractStringArray(rulesetSource, 'baseSpecies');
const exactSpecies = extractStringArray(rulesetSource, 'exactSpecies');
const derivedSpecies = extractStringArray(rulesetSource, 'derivedSpecies');
const includeMegaForms = /includeMegaForms:\s*true/.test(rulesetSource);

const gen = Generations.get(9);
const attackMoveIds = new Set(
  Array.from(gen.moves)
    .filter((move) => (move.category === 'Physical' || move.category === 'Special') && (move.basePower ?? 0) > 0)
    .map((move) => move.id),
);
const baseSpeciesSet = new Set(baseSpecies);
const selectableSpecies = new Set([...baseSpecies, ...exactSpecies, ...derivedSpecies]);
const speciesList = Array.from(gen.species)
  .filter((species) => {
    if (!species.name || !species.baseStats?.hp) return false;
    if (selectableSpecies.has(species.name)) return true;

    const baseName = species.baseSpecies ?? species.name;
    return includeMegaForms && species.name.includes('-Mega') && baseSpeciesSet.has(baseName);
  })
  .sort((left, right) => left.name.localeCompare(right.name, 'en'));

const output = {};
const emptySpecies = [];

for (const species of speciesList) {
  const learnsetMoveIds = await learnsetMoveIdsForSpecies(species);
  const attackMoves = uniqueSorted(learnsetMoveIds.filter((moveId) => attackMoveIds.has(moveId)));
  output[species.name] = attackMoves;

  if (attackMoves.length === 0) {
    emptySpecies.push(species.name);
  }
}

const content = `// Generated by scripts/generateLearnableAttackMoves.mjs.\n// Move IDs come from @pkmn/dex learnsets and are filtered to @smogon/calc physical/special moves.\n\nexport const LEARNABLE_ATTACK_MOVE_IDS_BY_SPECIES = ${JSON.stringify(output, null, 2)} as const;\n`;

fs.writeFileSync(OUTPUT_PATH, content);

console.log(JSON.stringify({
  species: speciesList.length,
  emptySpecies,
  outputPath: OUTPUT_PATH,
}, null, 2));
