import fs from 'node:fs';
import { Dex } from '@pkmn/dex';
import { Generations } from '@smogon/calc';

const RULESET_PATH = 'src/data/championsRulesets.ts';
const OUTPUT_PATH = 'src/data/pokemonAbilities.ts';
const DEX = Dex.forGen(9);

function extractStringArray(source, propertyName) {
  const match = source.match(new RegExp(`${propertyName}: \\[([\\s\\S]*?)\\]`));
  if (!match) {
    throw new Error(`Could not find ${propertyName} in ${RULESET_PATH}`);
  }

  return [...match[1].matchAll(/'([^']+)'/g)].map((item) => item[1]);
}

function uniqueSorted(values) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right, 'en'));
}

function abilityNamesForSpecies(species) {
  const dexSpecies = DEX.species.get(species.name) || Dex.species.get(species.name);
  const abilityNames = Object.values(dexSpecies?.abilities ?? species.abilities ?? {});
  return uniqueSorted(abilityNames.filter(Boolean));
}

const rulesetSource = fs.readFileSync(RULESET_PATH, 'utf8');
const baseSpecies = extractStringArray(rulesetSource, 'baseSpecies');
const exactSpecies = extractStringArray(rulesetSource, 'exactSpecies');
const derivedSpecies = extractStringArray(rulesetSource, 'derivedSpecies');
const includeMegaForms = /includeMegaForms:\s*true/.test(rulesetSource);

const gen = Generations.get(9);
const baseSpeciesSet = new Set(baseSpecies);
const selectableSpecies = new Set([...baseSpecies, ...exactSpecies, ...derivedSpecies]);
const speciesList = Array.from(gen.species)
  .filter((species) => {
    if (!species.name || !species.baseStats?.hp) return false;
    if (selectableSpecies.has(species.name)) return true;

    const baseName = species.baseSpecies ?? species.name;
    return includeMegaForms && species.name.includes('-Mega') && baseSpeciesSet.has(baseName);
  })
  .sort((left, right) => left.name.localeCompare(right.name, 'en'));

const output = {};
const emptySpecies = [];

for (const species of speciesList) {
  const abilities = abilityNamesForSpecies(species);
  output[species.name] = abilities;

  if (abilities.length === 0) {
    emptySpecies.push(species.name);
  }
}

const content = `// Generated by scripts/generatePokemonAbilities.mjs.\n// Ability names come from @pkmn/dex and are scoped to the active Pokemon Champions ruleset.\n\nexport const POKEMON_ABILITY_NAMES_BY_SPECIES = ${JSON.stringify(output, null, 2)} as const;\n`;

fs.writeFileSync(OUTPUT_PATH, content);

console.log(JSON.stringify({
  species: speciesList.length,
  emptySpecies,
  outputPath: OUTPUT_PATH,
}, null, 2));
