import { Generations } from '@smogon/calc';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const API = 'https://pokeapi.co/api/v2';
const GEN = Generations.get(9);
const OUTPUT = path.join(process.cwd(), 'src', 'data', 'moveKoreanNames.ts');
const LANGUAGE = 'ko';

const TYPE_LABELS = {
  Normal: '노말',
  Fighting: '격투',
  Flying: '비행',
  Poison: '독',
  Ground: '땅',
  Rock: '바위',
  Bug: '벌레',
  Ghost: '고스트',
  Steel: '강철',
  Fire: '불꽃',
  Water: '물',
  Grass: '풀',
  Electric: '전기',
  Psychic: '에스퍼',
  Ice: '얼음',
  Dragon: '드래곤',
  Dark: '악',
  Fairy: '페어리',
};

const MOVE_ALIASES = new Map([
  ['Vise Grip', 'vice-grip'],
]);

function normalizeKey(value) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

function simpleSlug(value) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function koName(entries = []) {
  return entries.find((entry) => entry.language?.name === LANGUAGE)?.name ?? null;
}

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Request failed ${response.status}: ${url}`);
  }
  return response.json();
}

async function mapLimit(items, limit, mapper) {
  const results = new Array(items.length);
  let cursor = 0;

  async function worker() {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await mapper(items[index], index);
    }
  }

  await Promise.all(Array.from({ length: limit }, worker));
  return results;
}

function buildMoveIndex(resources) {
  const exact = new Map();
  const normalized = new Map();

  for (const resource of resources) {
    exact.set(resource.name, resource);
    normalized.set(normalizeKey(resource.name), resource);
  }

  return { exact, normalized };
}

function hiddenPowerType(name) {
  const prefix = 'Hidden Power ';
  return name.startsWith(prefix) ? name.slice(prefix.length) : null;
}

function zMoveSlug(name, moveIndex) {
  const base = simpleSlug(name);
  return moveIndex.exact.has(`${base}--physical`) ? `${base}--physical` : null;
}

function pickMoveResource(name, moveIndex) {
  const alias = MOVE_ALIASES.get(name);
  if (alias) return { resource: moveIndex.exact.get(alias), kind: 'direct' };

  const hiddenType = hiddenPowerType(name);
  if (hiddenType) {
    return {
      resource: moveIndex.exact.get('hidden-power'),
      kind: 'hidden-power',
      suffix: TYPE_LABELS[hiddenType] ?? hiddenType,
    };
  }

  const slug = simpleSlug(name);
  const exact = moveIndex.exact.get(slug);
  if (exact) return { resource: exact, kind: 'direct' };

  const zSlug = zMoveSlug(name, moveIndex);
  if (zSlug) return { resource: moveIndex.exact.get(zSlug), kind: 'direct' };

  const normalized = moveIndex.normalized.get(normalizeKey(name));
  if (normalized) return { resource: normalized, kind: 'direct' };

  return { resource: null, kind: null };
}

async function main() {
  const moveList = await fetchJson(`${API}/move?limit=2000`);
  const moveIndex = buildMoveIndex(moveList.results);
  const moveCache = new Map();
  const smogonMoves = Array.from(GEN.moves)
    .filter((move) => (move.category === 'Physical' || move.category === 'Special') && (move.basePower ?? 0) > 0)
    .map((move) => move.name)
    .sort((a, b) => a.localeCompare(b, 'en'));

  const entries = await mapLimit(smogonMoves, 24, async (name) => {
    const picked = pickMoveResource(name, moveIndex);
    if (!picked.resource) return [name, name];

    const move = moveCache.get(picked.resource.url) ?? await fetchJson(picked.resource.url);
    moveCache.set(picked.resource.url, move);
    const baseName = koName(move.names) ?? name;
    const displayName = picked.kind === 'hidden-power' && picked.suffix
      ? `${baseName} (${picked.suffix})`
      : baseName;

    return [name, displayName];
  });

  const mapping = Object.fromEntries(entries);
  const unmapped = Object.entries(mapping)
    .filter(([name, korean]) => name === korean)
    .map(([name]) => name);
  const content = `// Generated by scripts/generateKoreanMoveNames.mjs.\n// PokeAPI does not include CAP/fan-made moves or G-Max signature moves, so those fall back to English.\n\nexport const MOVE_KOREAN_NAMES = ${JSON.stringify(mapping, null, 2)} as const;\n\nexport const UNMAPPED_MOVE_NAMES = ${JSON.stringify(unmapped, null, 2)} as const;\n`;

  await mkdir(path.dirname(OUTPUT), { recursive: true });
  await writeFile(OUTPUT, content, 'utf8');
  console.log(`Wrote ${OUTPUT}`);
  console.log(`Mapped ${entries.length - unmapped.length}/${entries.length}; fallback ${unmapped.length}`);
  if (unmapped.length > 0) {
    console.log(unmapped.join('\n'));
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
