import fs from 'node:fs';

const ABILITY_SOURCE_PATH = 'src/data/pokemonAbilities.ts';
const OUTPUT_PATH = 'src/data/abilityKoreanNames.ts';
const POKE_API_LIST_URL = 'https://pokeapi.co/api/v2/ability?limit=1000';
const CONCURRENCY = 12;
const MANUAL_OVERRIDES = {
  Eelevate: '천정부지',
  'Fire Mane': '불꽃갈기',
};

function extractAbilityNames(source) {
  return new Set([...source.matchAll(/^\s+"([^"]+)",?$/gm)].map((match) => match[1]));
}

async function fetchJson(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}: ${url}`);
  return response.json();
}

async function mapWithConcurrency(values, worker) {
  const result = [];
  let cursor = 0;
  async function run() {
    while (cursor < values.length) {
      const index = cursor;
      cursor += 1;
      result[index] = await worker(values[index]);
    }
  }
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, values.length) }, run));
  return result;
}

const source = fs.readFileSync(ABILITY_SOURCE_PATH, 'utf8');
const requiredAbilities = extractAbilityNames(source);
const list = await fetchJson(POKE_API_LIST_URL);
const entries = await mapWithConcurrency(list.results, async ({ url }) => {
  const ability = await fetchJson(url);
  const english = ability.names.find((name) => name.language.name === 'en')?.name;
  const korean = ability.names.find((name) => name.language.name === 'ko')?.name;
  return english && korean ? [english, korean] : null;
});
const names = Object.fromEntries(
  entries
    .filter(Boolean)
    .filter(([english]) => requiredAbilities.has(english))
    .sort(([left], [right]) => left.localeCompare(right, 'en')),
);
Object.assign(names, MANUAL_OVERRIDES);
const missing = [...requiredAbilities].filter((ability) => !names[ability]).sort();
const content = `// Generated by scripts/generateAbilityKoreanNames.mjs from PokeAPI.\n\nexport const ABILITY_KOREAN_NAMES: Record<string, string> = ${JSON.stringify(names, null, 2)};\n`;

fs.writeFileSync(OUTPUT_PATH, content);
console.log(JSON.stringify({ mapped: Object.keys(names).length, missing, outputPath: OUTPUT_PATH }, null, 2));
