// Generated by scripts/generatePokemonAbilities.mjs.
// Ability names come from @pkmn/dex and are scoped to the active Pokemon Champions ruleset.

export const POKEMON_ABILITY_NAMES_BY_SPECIES = {
  "Abomasnow": [
    "Snow Warning",
    "Soundproof"
  ],
  "Abomasnow-Mega": [
    "Snow Warning"
  ],
  "Absol": [
    "Justified",
    "Pressure",
    "Super Luck"
  ],
  "Absol-Mega": [
    "Magic Bounce"
  ],
  "Absol-Mega-Z": [
    "Magic Bounce"
  ],
  "Aegislash-Blade": [
    "Stance Change"
  ],
  "Aegislash-Shield": [
    "Stance Change"
  ],
  "Aerodactyl": [
    "Pressure",
    "Rock Head",
    "Unnerve"
  ],
  "Aerodactyl-Mega": [
    "Tough Claws"
  ],
  "Aggron": [
    "Heavy Metal",
    "Rock Head",
    "Sturdy"
  ],
  "Aggron-Mega": [
    "Filter"
  ],
  "Alakazam": [
    "Inner Focus",
    "Magic Guard",
    "Synchronize"
  ],
  "Alakazam-Mega": [
    "Trace"
  ],
  "Alcremie": [
    "Aroma Veil",
    "Sweet Veil"
  ],
  "Altaria": [
    "Cloud Nine",
    "Natural Cure"
  ],
  "Altaria-Mega": [
    "Pixilate"
  ],
  "Ampharos": [
    "Plus",
    "Static"
  ],
  "Ampharos-Mega": [
    "Mold Breaker"
  ],
  "Annihilape": [
    "Defiant",
    "Inner Focus",
    "Vital Spirit"
  ],
  "Appletun": [
    "Gluttony",
    "Ripen",
    "Thick Fat"
  ],
  "Araquanid": [
    "Water Absorb",
    "Water Bubble"
  ],
  "Arbok": [
    "Intimidate",
    "Shed Skin",
    "Unnerve"
  ],
  "Arcanine": [
    "Flash Fire",
    "Intimidate",
    "Justified"
  ],
  "Arcanine-Hisui": [
    "Flash Fire",
    "Intimidate",
    "Rock Head"
  ],
  "Archaludon": [
    "Stalwart",
    "Stamina",
    "Sturdy"
  ],
  "Ariados": [
    "Insomnia",
    "Sniper",
    "Swarm"
  ],
  "Armarouge": [
    "Flash Fire",
    "Weak Armor"
  ],
  "Aromatisse": [
    "Aroma Veil",
    "Healer"
  ],
  "Audino": [
    "Healer",
    "Klutz",
    "Regenerator"
  ],
  "Audino-Mega": [
    "Healer"
  ],
  "Aurorus": [
    "Refrigerate",
    "Snow Warning"
  ],
  "Avalugg": [
    "Ice Body",
    "Own Tempo",
    "Sturdy"
  ],
  "Avalugg-Hisui": [
    "Ice Body",
    "Strong Jaw",
    "Sturdy"
  ],
  "Azumarill": [
    "Huge Power",
    "Sap Sipper",
    "Thick Fat"
  ],
  "Banette": [
    "Cursed Body",
    "Frisk",
    "Insomnia"
  ],
  "Banette-Mega": [
    "Prankster"
  ],
  "Barbaracle": [
    "Pickpocket",
    "Sniper",
    "Tough Claws"
  ],
  "Barbaracle-Mega": [
    "Tough Claws"
  ],
  "Basculegion": [
    "Adaptability",
    "Mold Breaker",
    "Swift Swim"
  ],
  "Basculegion-F": [
    "Adaptability",
    "Mold Breaker",
    "Swift Swim"
  ],
  "Bastiodon": [
    "Soundproof",
    "Sturdy"
  ],
  "Beartic": [
    "Slush Rush",
    "Snow Cloak",
    "Swift Swim"
  ],
  "Beedrill": [
    "Sniper",
    "Swarm"
  ],
  "Beedrill-Mega": [
    "Adaptability"
  ],
  "Bellibolt": [
    "Damp",
    "Electromorphosis",
    "Static"
  ],
  "Blastoise": [
    "Rain Dish",
    "Torrent"
  ],
  "Blastoise-Mega": [
    "Mega Launcher"
  ],
  "Blaziken": [
    "Blaze",
    "Speed Boost"
  ],
  "Blaziken-Mega": [
    "Speed Boost"
  ],
  "Camerupt": [
    "Anger Point",
    "Magma Armor",
    "Solid Rock"
  ],
  "Camerupt-Mega": [
    "Sheer Force"
  ],
  "Castform": [
    "Forecast"
  ],
  "Castform-Rainy": [
    "Forecast"
  ],
  "Castform-Snowy": [
    "Forecast"
  ],
  "Castform-Sunny": [
    "Forecast"
  ],
  "Ceruledge": [
    "Flash Fire",
    "Weak Armor"
  ],
  "Chandelure": [
    "Flame Body",
    "Flash Fire",
    "Infiltrator"
  ],
  "Chandelure-Mega": [
    "Infiltrator"
  ],
  "Charizard": [
    "Blaze",
    "Solar Power"
  ],
  "Charizard-Mega-X": [
    "Tough Claws"
  ],
  "Charizard-Mega-Y": [
    "Drought"
  ],
  "Chesnaught": [
    "Bulletproof",
    "Overgrow"
  ],
  "Chesnaught-Mega": [
    "Bulletproof"
  ],
  "Chimecho": [
    "Levitate"
  ],
  "Chimecho-Mega": [
    "Levitate"
  ],
  "Clawitzer": [
    "Mega Launcher"
  ],
  "Clefable": [
    "Cute Charm",
    "Magic Guard",
    "Unaware"
  ],
  "Clefable-Mega": [
    "Magic Bounce"
  ],
  "Cofagrigus": [
    "Mummy"
  ],
  "Conkeldurr": [
    "Guts",
    "Iron Fist",
    "Sheer Force"
  ],
  "Corviknight": [
    "Mirror Armor",
    "Pressure",
    "Unnerve"
  ],
  "Crabominable": [
    "Anger Point",
    "Hyper Cutter",
    "Iron Fist"
  ],
  "Crabominable-Mega": [
    "Iron Fist"
  ],
  "Decidueye": [
    "Long Reach",
    "Overgrow"
  ],
  "Decidueye-Hisui": [
    "Overgrow",
    "Scrappy"
  ],
  "Dedenne": [
    "Cheek Pouch",
    "Pickup",
    "Plus"
  ],
  "Delphox": [
    "Blaze",
    "Magician"
  ],
  "Delphox-Mega": [
    "Levitate"
  ],
  "Diggersby": [
    "Cheek Pouch",
    "Huge Power",
    "Pickup"
  ],
  "Ditto": [
    "Imposter",
    "Limber"
  ],
  "Dragalge": [
    "Adaptability",
    "Poison Point",
    "Poison Touch"
  ],
  "Dragalge-Mega": [
    "Regenerator"
  ],
  "Dragapult": [
    "Clear Body",
    "Cursed Body",
    "Infiltrator"
  ],
  "Dragonite": [
    "Inner Focus",
    "Multiscale"
  ],
  "Dragonite-Mega": [
    "Multiscale"
  ],
  "Drampa": [
    "Berserk",
    "Cloud Nine",
    "Sap Sipper"
  ],
  "Drampa-Mega": [
    "Berserk"
  ],
  "Eelektross": [
    "Levitate"
  ],
  "Eelektross-Mega": [
    "Eelevate"
  ],
  "Emboar": [
    "Blaze",
    "Reckless"
  ],
  "Emboar-Mega": [
    "Mold Breaker"
  ],
  "Emolga": [
    "Motor Drive",
    "Static"
  ],
  "Empoleon": [
    "Competitive",
    "Torrent"
  ],
  "Espathra": [
    "Frisk",
    "Opportunist",
    "Speed Boost"
  ],
  "Espeon": [
    "Magic Bounce",
    "Synchronize"
  ],
  "Excadrill": [
    "Mold Breaker",
    "Sand Force",
    "Sand Rush"
  ],
  "Excadrill-Mega": [
    "Piercing Drill"
  ],
  "Falinks": [
    "Battle Armor",
    "Defiant"
  ],
  "Falinks-Mega": [
    "Defiant"
  ],
  "Farigiraf": [
    "Armor Tail",
    "Cud Chew",
    "Sap Sipper"
  ],
  "Feraligatr": [
    "Sheer Force",
    "Torrent"
  ],
  "Feraligatr-Mega": [
    "Dragonize"
  ],
  "Flapple": [
    "Gluttony",
    "Hustle",
    "Ripen"
  ],
  "Flareon": [
    "Flash Fire",
    "Guts"
  ],
  "Floette-Eternal": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Florges": [
    "Flower Veil",
    "Symbiosis"
  ],
  "Forretress": [
    "Overcoat",
    "Sturdy"
  ],
  "Froslass": [
    "Cursed Body",
    "Snow Cloak"
  ],
  "Froslass-Mega": [
    "Snow Warning"
  ],
  "Furfrou": [
    "Fur Coat"
  ],
  "Gallade": [
    "Justified",
    "Sharpness",
    "Steadfast"
  ],
  "Gallade-Mega": [
    "Inner Focus"
  ],
  "Garbodor": [
    "Aftermath",
    "Stench",
    "Weak Armor"
  ],
  "Garchomp": [
    "Rough Skin",
    "Sand Veil"
  ],
  "Garchomp-Mega": [
    "Sand Force"
  ],
  "Garchomp-Mega-Z": [
    "Sand Force"
  ],
  "Gardevoir": [
    "Synchronize",
    "Telepathy",
    "Trace"
  ],
  "Gardevoir-Mega": [
    "Pixilate"
  ],
  "Garganacl": [
    "Clear Body",
    "Purifying Salt",
    "Sturdy"
  ],
  "Gengar": [
    "Cursed Body"
  ],
  "Gengar-Mega": [
    "Shadow Tag"
  ],
  "Gholdengo": [
    "Good as Gold"
  ],
  "Glaceon": [
    "Ice Body",
    "Snow Cloak"
  ],
  "Glalie": [
    "Ice Body",
    "Inner Focus",
    "Moody"
  ],
  "Glalie-Mega": [
    "Refrigerate"
  ],
  "Glimmora": [
    "Corrosion",
    "Toxic Debris"
  ],
  "Glimmora-Mega": [
    "Adaptability"
  ],
  "Gliscor": [
    "Hyper Cutter",
    "Poison Heal",
    "Sand Veil"
  ],
  "Golurk": [
    "Iron Fist",
    "Klutz",
    "No Guard"
  ],
  "Golurk-Mega": [
    "Unseen Fist"
  ],
  "Goodra": [
    "Gooey",
    "Hydration",
    "Sap Sipper"
  ],
  "Goodra-Hisui": [
    "Gooey",
    "Sap Sipper",
    "Shell Armor"
  ],
  "Gourgeist": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Large": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Small": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Gourgeist-Super": [
    "Frisk",
    "Insomnia",
    "Pickup"
  ],
  "Greninja": [
    "Battle Bond",
    "Protean",
    "Torrent"
  ],
  "Greninja-Mega": [
    "Protean"
  ],
  "Grimmsnarl": [
    "Frisk",
    "Pickpocket",
    "Prankster"
  ],
  "Gyarados": [
    "Intimidate",
    "Moxie"
  ],
  "Gyarados-Mega": [
    "Mold Breaker"
  ],
  "Hatterene": [
    "Anticipation",
    "Healer",
    "Magic Bounce"
  ],
  "Hawlucha": [
    "Limber",
    "Mold Breaker",
    "Unburden"
  ],
  "Hawlucha-Mega": [
    "No Guard"
  ],
  "Heliolisk": [
    "Dry Skin",
    "Sand Veil",
    "Solar Power"
  ],
  "Heracross": [
    "Guts",
    "Moxie",
    "Swarm"
  ],
  "Heracross-Mega": [
    "Skill Link"
  ],
  "Hippowdon": [
    "Sand Force",
    "Sand Stream"
  ],
  "Houndoom": [
    "Early Bird",
    "Flash Fire",
    "Unnerve"
  ],
  "Houndoom-Mega": [
    "Solar Power"
  ],
  "Houndstone": [
    "Fluffy",
    "Sand Rush"
  ],
  "Hydrapple": [
    "Regenerator",
    "Sticky Hold",
    "Supersweet Syrup"
  ],
  "Hydreigon": [
    "Levitate"
  ],
  "Incineroar": [
    "Blaze",
    "Intimidate"
  ],
  "Infernape": [
    "Blaze",
    "Iron Fist"
  ],
  "Jolteon": [
    "Quick Feet",
    "Volt Absorb"
  ],
  "Kangaskhan": [
    "Early Bird",
    "Inner Focus",
    "Scrappy"
  ],
  "Kangaskhan-Mega": [
    "Parental Bond"
  ],
  "Kingambit": [
    "Defiant",
    "Pressure",
    "Supreme Overlord"
  ],
  "Kleavor": [
    "Sharpness",
    "Sheer Force",
    "Swarm"
  ],
  "Klefki": [
    "Magician",
    "Prankster"
  ],
  "Kommo-o": [
    "Bulletproof",
    "Overcoat",
    "Soundproof"
  ],
  "Krookodile": [
    "Anger Point",
    "Intimidate",
    "Moxie"
  ],
  "Leafeon": [
    "Chlorophyll",
    "Leaf Guard"
  ],
  "Liepard": [
    "Limber",
    "Prankster",
    "Unburden"
  ],
  "Lopunny": [
    "Cute Charm",
    "Klutz",
    "Limber"
  ],
  "Lopunny-Mega": [
    "Scrappy"
  ],
  "Lucario": [
    "Inner Focus",
    "Justified",
    "Steadfast"
  ],
  "Lucario-Mega": [
    "Adaptability"
  ],
  "Lucario-Mega-Z": [
    "Adaptability"
  ],
  "Luxray": [
    "Guts",
    "Intimidate",
    "Rivalry"
  ],
  "Lycanroc": [
    "Keen Eye",
    "Sand Rush",
    "Steadfast"
  ],
  "Lycanroc-Dusk": [
    "Tough Claws"
  ],
  "Lycanroc-Midnight": [
    "Keen Eye",
    "No Guard",
    "Vital Spirit"
  ],
  "Machamp": [
    "Guts",
    "No Guard",
    "Steadfast"
  ],
  "Malamar": [
    "Contrary",
    "Infiltrator",
    "Suction Cups"
  ],
  "Malamar-Mega": [
    "Contrary"
  ],
  "Mamoswine": [
    "Oblivious",
    "Snow Cloak",
    "Thick Fat"
  ],
  "Manectric": [
    "Lightning Rod",
    "Minus",
    "Static"
  ],
  "Manectric-Mega": [
    "Intimidate"
  ],
  "Maushold": [
    "Cheek Pouch",
    "Friend Guard",
    "Technician"
  ],
  "Mawile": [
    "Hyper Cutter",
    "Intimidate",
    "Sheer Force"
  ],
  "Mawile-Mega": [
    "Huge Power"
  ],
  "Medicham": [
    "Pure Power",
    "Telepathy"
  ],
  "Medicham-Mega": [
    "Pure Power"
  ],
  "Meganium": [
    "Leaf Guard",
    "Overgrow"
  ],
  "Meganium-Mega": [
    "Mega Sol"
  ],
  "Meowscarada": [
    "Overgrow",
    "Protean"
  ],
  "Meowstic": [
    "Infiltrator",
    "Keen Eye",
    "Prankster"
  ],
  "Meowstic-F": [
    "Competitive",
    "Infiltrator",
    "Keen Eye"
  ],
  "Meowstic-F-Mega": [
    "Trace"
  ],
  "Meowstic-M-Mega": [
    "Trace"
  ],
  "Metagross": [
    "Clear Body",
    "Light Metal"
  ],
  "Metagross-Mega": [
    "Tough Claws"
  ],
  "Milotic": [
    "Competitive",
    "Cute Charm",
    "Marvel Scale"
  ],
  "Mimikyu": [
    "Disguise"
  ],
  "Morpeko": [
    "Hunger Switch"
  ],
  "Mr. Rime": [
    "Ice Body",
    "Screen Cleaner",
    "Tangled Feet"
  ],
  "Mudsdale": [
    "Inner Focus",
    "Own Tempo",
    "Stamina"
  ],
  "Musharna": [
    "Forewarn",
    "Synchronize",
    "Telepathy"
  ],
  "Ninetales": [
    "Drought",
    "Flash Fire"
  ],
  "Ninetales-Alola": [
    "Snow Cloak",
    "Snow Warning"
  ],
  "Noivern": [
    "Frisk",
    "Infiltrator",
    "Telepathy"
  ],
  "Oranguru": [
    "Inner Focus",
    "Symbiosis",
    "Telepathy"
  ],
  "Orthworm": [
    "Earth Eater",
    "Sand Veil"
  ],
  "Overqwil": [
    "Intimidate",
    "Poison Point",
    "Swift Swim"
  ],
  "Palafin": [
    "Zero to Hero"
  ],
  "Palafin-Hero": [
    "Zero to Hero"
  ],
  "Pangoro": [
    "Iron Fist",
    "Mold Breaker",
    "Scrappy"
  ],
  "Passimian": [
    "Defiant",
    "Receiver"
  ],
  "Pelipper": [
    "Drizzle",
    "Keen Eye",
    "Rain Dish"
  ],
  "Pidgeot": [
    "Big Pecks",
    "Keen Eye",
    "Tangled Feet"
  ],
  "Pidgeot-Mega": [
    "No Guard"
  ],
  "Pikachu": [
    "Lightning Rod",
    "Static"
  ],
  "Pinsir": [
    "Hyper Cutter",
    "Mold Breaker",
    "Moxie"
  ],
  "Pinsir-Mega": [
    "Aerilate"
  ],
  "Politoed": [
    "Damp",
    "Drizzle",
    "Water Absorb"
  ],
  "Polteageist": [
    "Cursed Body",
    "Weak Armor"
  ],
  "Primarina": [
    "Liquid Voice",
    "Torrent"
  ],
  "Pyroar": [
    "Moxie",
    "Rivalry",
    "Unnerve"
  ],
  "Pyroar-Mega": [
    "Fire Mane"
  ],
  "Quaquaval": [
    "Moxie",
    "Torrent"
  ],
  "Qwilfish": [
    "Intimidate",
    "Poison Point",
    "Swift Swim"
  ],
  "Raichu": [
    "Lightning Rod",
    "Static"
  ],
  "Raichu-Alola": [
    "Surge Surfer"
  ],
  "Raichu-Mega-X": [
    "Electric Surge"
  ],
  "Raichu-Mega-Y": [
    "No Guard"
  ],
  "Rampardos": [
    "Mold Breaker",
    "Sheer Force"
  ],
  "Reuniclus": [
    "Magic Guard",
    "Overcoat",
    "Regenerator"
  ],
  "Rhyperior": [
    "Lightning Rod",
    "Reckless",
    "Solid Rock"
  ],
  "Roserade": [
    "Natural Cure",
    "Poison Point",
    "Technician"
  ],
  "Rotom": [
    "Levitate"
  ],
  "Rotom-Fan": [
    "Levitate"
  ],
  "Rotom-Frost": [
    "Levitate"
  ],
  "Rotom-Heat": [
    "Levitate"
  ],
  "Rotom-Mow": [
    "Levitate"
  ],
  "Rotom-Wash": [
    "Levitate"
  ],
  "Runerigus": [
    "Wandering Spirit"
  ],
  "Sableye": [
    "Keen Eye",
    "Prankster",
    "Stall"
  ],
  "Sableye-Mega": [
    "Magic Bounce"
  ],
  "Salazzle": [
    "Corrosion",
    "Oblivious"
  ],
  "Samurott": [
    "Shell Armor",
    "Torrent"
  ],
  "Samurott-Hisui": [
    "Sharpness",
    "Torrent"
  ],
  "Sandaconda": [
    "Sand Spit",
    "Sand Veil",
    "Shed Skin"
  ],
  "Sceptile": [
    "Overgrow",
    "Unburden"
  ],
  "Sceptile-Mega": [
    "Lightning Rod"
  ],
  "Scizor": [
    "Light Metal",
    "Swarm",
    "Technician"
  ],
  "Scizor-Mega": [
    "Technician"
  ],
  "Scolipede": [
    "Poison Point",
    "Speed Boost",
    "Swarm"
  ],
  "Scolipede-Mega": [
    "Shell Armor"
  ],
  "Scovillain": [
    "Chlorophyll",
    "Insomnia",
    "Moody"
  ],
  "Scovillain-Mega": [
    "Spicy Spray"
  ],
  "Scrafty": [
    "Intimidate",
    "Moxie",
    "Shed Skin"
  ],
  "Scrafty-Mega": [
    "Intimidate"
  ],
  "Serperior": [
    "Contrary",
    "Overgrow"
  ],
  "Sharpedo": [
    "Rough Skin",
    "Speed Boost"
  ],
  "Sharpedo-Mega": [
    "Strong Jaw"
  ],
  "Simipour": [
    "Gluttony",
    "Torrent"
  ],
  "Simisage": [
    "Gluttony",
    "Overgrow"
  ],
  "Simisear": [
    "Blaze",
    "Gluttony"
  ],
  "Sinistcha": [
    "Heatproof",
    "Hospitality"
  ],
  "Skarmory": [
    "Keen Eye",
    "Sturdy",
    "Weak Armor"
  ],
  "Skarmory-Mega": [
    "Stalwart"
  ],
  "Skeledirge": [
    "Blaze",
    "Unaware"
  ],
  "Slowbro": [
    "Oblivious",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowbro-Galar": [
    "Own Tempo",
    "Quick Draw",
    "Regenerator"
  ],
  "Slowbro-Mega": [
    "Shell Armor"
  ],
  "Slowking": [
    "Oblivious",
    "Own Tempo",
    "Regenerator"
  ],
  "Slowking-Galar": [
    "Curious Medicine",
    "Own Tempo",
    "Regenerator"
  ],
  "Slurpuff": [
    "Sweet Veil",
    "Unburden"
  ],
  "Sneasler": [
    "Poison Touch",
    "Pressure",
    "Unburden"
  ],
  "Snorlax": [
    "Gluttony",
    "Immunity",
    "Thick Fat"
  ],
  "Spiritomb": [
    "Infiltrator",
    "Pressure"
  ],
  "Staraptor": [
    "Intimidate",
    "Reckless"
  ],
  "Staraptor-Mega": [
    "Contrary"
  ],
  "Starmie": [
    "Analytic",
    "Illuminate",
    "Natural Cure"
  ],
  "Starmie-Mega": [
    "Huge Power"
  ],
  "Steelix": [
    "Rock Head",
    "Sheer Force",
    "Sturdy"
  ],
  "Steelix-Mega": [
    "Sand Force"
  ],
  "Stunfisk": [
    "Limber",
    "Sand Veil",
    "Static"
  ],
  "Stunfisk-Galar": [
    "Mimicry"
  ],
  "Swampert": [
    "Damp",
    "Torrent"
  ],
  "Swampert-Mega": [
    "Swift Swim"
  ],
  "Sylveon": [
    "Cute Charm",
    "Pixilate"
  ],
  "Talonflame": [
    "Flame Body",
    "Gale Wings"
  ],
  "Tauros": [
    "Anger Point",
    "Intimidate",
    "Sheer Force"
  ],
  "Tauros-Paldea-Aqua": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Tauros-Paldea-Blaze": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Tauros-Paldea-Combat": [
    "Anger Point",
    "Cud Chew",
    "Intimidate"
  ],
  "Tinkaton": [
    "Mold Breaker",
    "Own Tempo",
    "Pickpocket"
  ],
  "Torkoal": [
    "Drought",
    "Shell Armor",
    "White Smoke"
  ],
  "Torterra": [
    "Overgrow",
    "Shell Armor"
  ],
  "Toucannon": [
    "Keen Eye",
    "Sheer Force",
    "Skill Link"
  ],
  "Toxapex": [
    "Limber",
    "Merciless",
    "Regenerator"
  ],
  "Toxicroak": [
    "Anticipation",
    "Dry Skin",
    "Poison Touch"
  ],
  "Trevenant": [
    "Frisk",
    "Harvest",
    "Natural Cure"
  ],
  "Tsareena": [
    "Leaf Guard",
    "Queenly Majesty",
    "Sweet Veil"
  ],
  "Typhlosion": [
    "Blaze",
    "Flash Fire"
  ],
  "Typhlosion-Hisui": [
    "Blaze",
    "Frisk"
  ],
  "Tyranitar": [
    "Sand Stream",
    "Unnerve"
  ],
  "Tyranitar-Mega": [
    "Sand Stream"
  ],
  "Tyrantrum": [
    "Rock Head",
    "Strong Jaw"
  ],
  "Umbreon": [
    "Inner Focus",
    "Synchronize"
  ],
  "Vanilluxe": [
    "Ice Body",
    "Snow Warning",
    "Weak Armor"
  ],
  "Vaporeon": [
    "Hydration",
    "Water Absorb"
  ],
  "Venusaur": [
    "Chlorophyll",
    "Overgrow"
  ],
  "Venusaur-Mega": [
    "Thick Fat"
  ],
  "Victreebel": [
    "Chlorophyll",
    "Gluttony"
  ],
  "Victreebel-Mega": [
    "Innards Out"
  ],
  "Vileplume": [
    "Chlorophyll",
    "Effect Spore"
  ],
  "Vivillon-Fancy": [
    "Compound Eyes",
    "Friend Guard",
    "Shield Dust"
  ],
  "Volcarona": [
    "Flame Body",
    "Swarm"
  ],
  "Watchog": [
    "Analytic",
    "Illuminate",
    "Keen Eye"
  ],
  "Weavile": [
    "Pickpocket",
    "Pressure"
  ],
  "Whimsicott": [
    "Chlorophyll",
    "Infiltrator",
    "Prankster"
  ],
  "Wyrdeer": [
    "Frisk",
    "Intimidate",
    "Sap Sipper"
  ],
  "Zoroark": [
    "Illusion"
  ],
  "Zoroark-Hisui": [
    "Illusion"
  ]
} as const;
